// Import file Global.css

import Link from "@/node_modules/next/link";
import "../app/globals.css"


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en">
      <body>

        {/* Main Content */}
        <section>
          {children}
        </section>

        {/* Footer */}
        <footer className="footer footer-center bg-blue-500 text-white rounded p-10">
          <nav className="grid grid-flow-col gap-4">
            <p>Follows Our Socials</p>
          </nav>
          <aside>
            <Link href={'/dashboard'}>
              Copyright ©2024 - Barang Second - Vanguard
            </Link>
          </aside>
        </footer>
      </body>
    </html>
  );
}
